=== Andres-Perez-Leonis/TrabajosUMH/Tecnologias_Web/Practica1/Ej1/P2/P_1_2.dtd
<!ELEMENT novedades (podcast+)>
<!ELEMENT podcast (imagen, titulo, responsable)>
<!ELEMENT imagen EMPTY>
<!ATTLIST imagen src CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT responsable (#PCDATA)>

=== Andres-Perez-Leonis/TrabajosUMH/Tecnologias_Web/Practica1/Ej1/P2/P1_1_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE novedades SYSTEM "P_1_2.dtd">

<novedades>
    <podcast>
        <imagen src=""></imagen>
        <titulo>Fuera de Series: Semana del 9 al 15 de Octubre de 2023, 6 de octubre de 2023</titulo>
        <responsable>FUERA DE SERIES</responsable>
    </podcast>
    
    <podcast>
        <imagen src=""></imagen>
        <titulo>La Universidad Miguel Hernández pone en marcha las actividades de Bienvenida...</titulo>
        <responsable>INFORMATIVOS UMH</responsable>
    </podcast>
    
    <podcast>
        <imagen src=""></imagen>
        <titulo>El estreno de la actualidad deportiva, en “The post radio”, 6 de octubre...</titulo>
        <responsable>THE POST RADIO</responsable>
    </podcast>
    
    <podcast>
        <imagen src=""></imagen>
        <titulo>UMH Sapiens nos descubre todo sobre las investigaciones del ingeniero Agroalimentario...</titulo>
        <responsable>INFORMATIVOS UMH</responsable>
    </podcast>

</novedades>
