=== Andres-Perez-Leonis/TrabajosUMH/Tecnologias_Web/Practica1/Ej1/P3/P1_1_3.dtd
<!ELEMENT podcast (imagen, titulo, fecha, categoria, audio, descripcion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT audio (#PCDATA)>
<!ATTLIST audio src CDATA #REQUIRED>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT imagen EMPTY>
<!ATTLIST imagen src CDATA #REQUIRED>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT parrafo (#PCDATA)>
<!ELEMENT descripcion (texto, enlace)>
<!ELEMENT enlace (texto, direccion)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT fecha EMPTY>
<!ATTLIST fecha dd CDATA #REQUIRED >
<!ATTLIST fecha mm CDATA #REQUIRED > 
<!ATTLIST fecha aaaa CDATA #IMPLIED >

=== Andres-Perez-Leonis/TrabajosUMH/Tecnologias_Web/Practica1/Ej1/P3/P1_1_3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE podcast SYSTEM "P1_1_3.dtd">

<podcast>
    <imagen src=""></imagen>
    <titulo>
    </titulo>
    <fecha dd="" mm="" aaaa=""></fecha>
    <categoria>Mundo y Sociedad</categoria>
    <audio src="">Reproducir</audio>
    <descripcion>
        <texto>
        </texto>
        <enlace>
            <texto></texto>
            <direccion></direccion>
        </enlace>
    </descripcion>
</podcast>

<!--Aqui tenemos que explicar que aÃ±adiriamos al dtd y como (en la memoria)-->
